### PR TITLE
Fix and update query bar in MAGI

### PR DESCRIPTION
**Pull request by connorgr**
This pull request adds small aesthetic improvements and several usability improvements and bugfixes.
1. A logged in user now sees their recent queries in the navbar and the query fields are prepopulated with their most recent query
2. Add gene button moved to typeahead menu
3. The add gene input field flashes green on successful gene add
4. The dataset multiselect menu no longer remains stuck on click-out
5. Gene input field now displays correct text when typed in
6. Query is now removed from MAGI's control panel
7. Linted several files and resolved onLoad errors

### CODE REVIEW

**Comment by mdml** [comment]
A couple of comments:
- Did you try using session variables? I think it'd be much nicer if users didn't have to log in to have query persistence, since we'd probably expect anonymous users to use the sample view (which was the original motivation for the requery bar).
- Is it possible to modify `routes/requery.js` and `routes/index.js` to use a common function to create the checkboxes, etc? I noticed this redundancy when fixing the bug yesterday which required me to modify the same code in multiple places.

**Comment by connorgr** [comment]
See nav-query.js:115 and the requery route for session variable tracking changes to accomodate users who are not signed in.

Re: code redundancy, are you talking about the Dataset and Gene lookup and parsing code?

**Comment by mdml** [comment]
**Current pull request**
The changes look good to me. I guess we were using the session to store 401 messages?

One other quick thought. Perhaps we should modify the gene dropdown to say how many genes have already been selected, e.g.
screen shot 2015-07-12 at 10 52 02 am

**Code Redundancy**
Yes, I was talking about lines 7 to ~60 in `routes/requery.js`. This doesn't have to do with this pull request but I thought I'd mention it anyway.

**Comment by connorgr** [comment]
The gene dropdown's been modified. See commit e95a028. Yeah; it looked like 401s.

**Comment by mdml** [comment]
LGTM. Let's review with Ben today and merge?

**Pull request merged**
