### PR TITLE
Add dataset requery option in MAGI query view

### PR DESCRIPTION
**Pull request by connorgr**
This adds a new collapse menu to the MAGI control panel that allows users to modify their query's dataset within the query view.

### CODE REVIEW

**Comment by connorgr** [comment]
Should this be expanded to include a text box for new genes and checkboxes to remove existing genes? Additional bug checking with current implementation would be a plus.

**Comment by mdml** [comment]
I think you forgot to commit some files, e.g. `routes/requery.js`?

**Comment by connorgr** [comment]
Added.

**Comment by mdml** [comment]
LGTM. I think a search box for genes and a separate one for datasets would be ideal. Then current genes/datasets can be listed above with 'x-out' buttons? What do you think?

I'm going to post this to our testing server so others can take a look.

**Comment by connorgr** [comment]
Similar to searching for StackOverflow tags on posts, rather than a multiselect list, then? I'm all for that. Should be easy enough to do – just an array of all genes and all datasets to the client.

One thing I'm not sure how to handle is if there is a name collision between a user supplied dataset and a public dataset. Or even between user datasets. In the multiselect this is handled by branching, but I'm not sure how that'd be doable in this search. Maybe prepend the source (e.g., "public - BLCA") to the name? This gets verbose though.

**Comment by connorgr** [comment]
Updated with revisions to add genes to the sidebar.

**Comment by mdml** [comment]
Looks great! One comment is that we absolutely need to _automatically_ capitalize genes when adding them in the "re"-query box.

Other, less important questions/comments:
- Is there any way to do autocomplete when entering genes? Should be pretty easy using [Twitter Typeahead](https://twitter.github.io/typeahead.js/), which we already use for annotations in the view.
- I see you added `routes/requery.js`. Is that called by both `routes/index.js` and `routes/view.js`?
- It'd be great if we could move the whole query panel to a fixed bar along the top (but perhaps better suited for a whole "view" redesign?).

**Comment by connorgr** [comment]
The autocapitalization is now included on-add for the query gene input.
- I think to do autocomplete we'd need a json file sent to the client with a full gene index listing or frequent GET requests to the server. I was thinking that autocomplete would be a good feature too, but I wasn't sure if the system requirements (bandwith or number of pings) would be too demanding.
- My post-vacation brain looking at the server-side code tells me that the requery route is independent of both the index and view routes as it is only triggered by AJAX requests from the client, opposed to bundled-in to the on-load requests.
- Definitely, but I think more inline with the view redesign.

**Pull request merged**
