### PR TITLE
Fix query bar bugs

### PR DESCRIPTION
**Pull request by connorgr**
Makes the gene list scrollable with more genes to cover cases like "TP53" which returns so many variants, that the plain would TP53 fall off the menu. Also removed form submission on enter key press for the gene bar so that no sever errors occurs.

### CODE REVIEW

**Comment by mdml** [comment]
Looks great! I found a few bugs from earlier patches that I also fixed.

One other request: could you also make the sample view typeahead (pictured below) scrollable?
screen shot 2015-07-21 at 10 26 53 am

**Comment by mdml** [comment]
Also, just improved the gene search regex to:
- Match the beginning of the string instead of substrings
- Sort first by length then by character ascending (so exact matches are first)

**Comment by connorgr** [comment]
Sample search updated in cb2fa68

**Comment by mdml** [comment]
LGTM :white_check_mark:

**Pull request merged**
